## 1. Instalar
#  sudo pacman -S mpd mpc rmpc

## 2. Criar diretórios e arquivos (só o necessário para sua config)
#  mkdir -p ~/.config/mpd/playlists ~/Músicas
#  touch ~/.config/mpd/mpd.db ~/.config/mpd/mpd.log

## 3. Editar o mpd.conf
#  nano ~/.config/mpd/mpd.conf

## 4. Subir o serviço
#  systemctl --user enable --now mpd
#  systemctl --user status mpd

## 5. Configurar o rmpc (gera o config padrão)
#  rmpc config

## 6. Atualizar a biblioteca
#  mpc update

## 7. Abrir
#  rmpc


# Diretório de música (ajuste para o seu caminho)
music_directory     "~/Músicas"

# Diretório de playlists
playlist_directory "~/.config/mpd/playlists"

# Banco de dados (arquivo que armazena a biblioteca musical)
db_file            "~/.config/mpd/mpd.db"

# Log (opcional)
log_file           "~/.config/mpd/mpd.log"

# Configuração do áudio (saída padrão para PulseAudio/ALSA)
#audio_output {
    #type            "pulse"  
    #name            "MPD Output"
#}

audio_output {
    type    "pipewire"
    name    "MPD Output"
}

# Permissões (opcional, para evitar problemas de acesso)
#user               "sidiclei"  # Substitua pelo seu nome de usuário
bind_to_address    "127.0.0.1"     # Restringe ao localhost (mais seguro)
port               "6600"          # Porta padrão do MPD
