# ~/.config/i3/modules/decoration.conf
# Configurações de aparência e temas

# Fonts
font pango:SF Pro Display Regular 13
#font pango:JetBrains Mono:style=Regular:pixelsize=13
#font pango:Cantarell:style=Bold:pixelsize=11
#font pango:Source Sans Pro 12
#font pango:Open Sans Semibold 10
#font pango:Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid
#font pango:Iosevka Custom 11
#font pango:monospace 8
#font pango:FiraCode 8
#font pango:Fantasque Sans Mono 8
#font pango:Poppins 8
#font pango:DejaVu Sans Mono 8
#font pango:Noto Sans 12

# Window Borders and Focus
# Aplica borda de 3 pixels a TODAS as janelas (regex ^.* casa com qualquer classe e qualquer título),
# esta regra sobrescreva o default_border
#for_window [class="^.*" title="^.*"] border pixel 3
# Borda padrão para janelas em tile
default_border pixel 3
# Sem borda com título para flutuantes
default_floating_border none
# Esconde bordas quando só uma janela
hide_edge_borders smart
# Centraliza títulos nas janelas flutuantes
title_align center

# Mais sutil'smart'
focus_on_window_activation focus
# Permite circular entre containers
focus_wrapping yes
# Cursor segue entre outputs
mouse_warping output

# Icon Variables (Font Awesome)
set $ico_bank <span font='Font Awesome'>&#xf155;</span>       #  Bank
set $ico_chat <span font='Font Awesome'>&#xf27b;</span>       #  Chat
set $ico_chrome <span font='Font Awesome'>&#xf268;</span>     #  Chrome
set $ico_code <span font='Font Awesome'>&#xf121;</span>       #  Code
set $ico_document <span font='Font Awesome'>&#xf0f6;</span>   #  Document
set $ico_editor <span font='Font Awesome'>&#xf044;</span>     #  Editor
set $ico_email <span font='Font Awesome'>&#xf003;</span>      #  Email
set $ico_firefox <span font='Font Awesome'>&#xf269;</span>    #  Firefox
set $ico_folder <span font='Font Awesome'>&#xf115;</span>     #  Folder
set $ico_github <span font='Font Awesome'>&#xf09b;</span>     #  GitHub
set $ico_hangouts <span font='Font Awesome'>&#xf10e;</span>   #  Hangouts
set $ico_menu <span font='Font Awesome'>&#xf0c9;</span>       #  Menu
set $ico_monitor <span font='Font Awesome'>&#xf26c;</span>    #  Monitor
set $ico_music <span font='Font Awesome'>&#xf001;</span>      #  Music
set $ico_news <span font='Font Awesome'>&#xf09e;</span>       #  News
set $ico_package <span font='Font Awesome'>&#xf1c6;</span>    #  Package
set $ico_play <span font='Font Awesome'>&#xf01d;</span>       #  Play
set $ico_table <span font='Font Awesome'>&#xf0ce;</span>      #  Table
set $ico_telegram <span font='Font Awesome'>&#xf1d9;</span>   #  Telegram
set $ico_terminal <span font='Font Awesome'>&#xf120;</span>   #  Terminal
set $ico_video <span font='Font Awesome'>&#xf008;</span>      #  Video
set $ico_volume <span font='Font Awesome'>&#xf028;</span>     #  Volume
set $ico_whatsapp <span font='Font Awesome'>&#xf232;</span>   #  WhatsApp
set $ico_window <span font='Font Awesome'>&#xf2d0;</span>     #  Window

## COLORS (Xresources integration)
set_from_resource $fg           i3wm.color7  #f3f4f5
set_from_resource $bg           i3wm.color3  #2E3440
set_from_resource $id           i3wm.color15 #D8DEE9
set_from_resource $inactive     i3wm.color8  #676E7D
set_from_resource $urgent       i3wm.color1  #E53935

# Variável para o indicador de split ::
set $sc #00ff00

# Window Color Configuration
#client.<classe>        <border>    <background>  <text>       <indicator>  <child_border>
client.focused           $id         $id           $bg          $sc          $id
client.focused_inactive  $bg         $bg           $inactive    $bg          $bg
client.unfocused         $inactive   $bg           $inactive    $bg          $bg
client.urgent            $urgent     $urgent       $fg          $bg          $urgent
client.placeholder       $bg         $bg           $fg          $bg          $bg
client.background        $bg
