# ~/.config/i3/modules/input.conf
# Configurações de dispositivos de entrada

# Mouse(Mapeamento xev) ==> Se você não sabe o número do botão do mouse: xev | grep button
# Botões laterais= 8 e 9 - scroll direita/esquerda= 6 e 7 - rolagem cima/baixo= 4 e 5

# # Modifier key ALT para arrastar janelas flutuantes
floating_modifier $alt  

# Window operations
# Botão meio (barra título) → fecha janela
bindsym --release button2 kill 
# Mod4 + botão meio → força fechar          
bindsym --whole-window $win+button2 kill
# Mod4 + botão direito → alterna flutuante 
$sup+button3 --whole-window floating toggle  

# Window movement with mouse
# Botões de rolagem lateral (mapeados via xev):
# Scroll esquerdo → move janela ←
bindsym --whole-window button6 move left
# Scroll direito → move janela →   
bindsym --whole-window button7 move right  

# Arrasto das janelas pelo título (experimental)
# tiling_drag modifier titlebar  te
