# ~/.config/i3/modules/misc.conf
# Configurações diversas e complementares

# ========== SCREEN OPERATIONS ==========
# Área selecionada
bindsym --release Mod4+Print $exe sh -c 'mkdir -p $HOME/Imagens/Screenshots/ && flameshot gui'
# Tela inteira com cópia para clipboard
bindsym --release Print $exe sh -c 'mkdir -p $HOME/Imagens/Screenshots/ && flameshot full -c -p $HOME/Imagens/Screenshots'
# Selecionada a Janela com clique e cópia para clipboard
bindsym --release Mod4+j $exe sh -c 'mkdir -p $HOME/Imagens/Screenshots/ && cd $HOME/Imagens/Screenshots/ && scrot -s -b -e "xclip -selection clipboard -t image/png -i \$f && notify-send -i camera-photo '\''Screenshot'\'' '\''✓ Copiada para clipboard\n✓ Salva em Screenshots'\''"'
 
# Screen recording
$sup+g $exe $scriptdir/launch_ssrecorder.sh &
#$sup+g $exe simplescreenrecorder --start-hidden 

# OCR, BarCode and QR tools
bindsym $alt+o $exe $scriptdir/image_to_text.sh
bindsym $alt+q $exe $scriptdir/qrscan.sh
bindsym $alt+b $exe $scriptdir/barcode_scan.sh

# ========== MEDIA BINDINGS ==========
# Volume control
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +10% && $vol_signal 
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -10% && $vol_signal
bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle && $vol_signal  

# Microphone - Mute/Unmute microfone
bindsym XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle  

# Media playback
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioStop exec playerctl stop
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous    

# Brightness
bindsym XF86MonBrightnessUp exec xbacklight -inc 20 
bindsym XF86MonBrightnessDown exec xbacklight -dec 20  

# ========== NOTIFICATION CONTROLS ==========
bindsym Ctrl+space             $exe dunstctl close   
bindsym Ctrl+Shift+space       $exe dunstctl close-all     
bindsym Ctrl+comma             $exe dunstctl history-pop
bindsym Ctrl+period            $exe dunstctl context        
