# ----------------------------------------------------------------------------
# STATUS BAR
# ----------------------------------------------------------------------------

#bar {        
#        $out_pri
#        position top
#        wheel_up_cmd nop
#        wheel_down_cmd nop
#        tray_padding 4

#        mode dock

#        mode hide
#        hidden_state hide
#        modifier Mod4

#        separator_symbol "|"
#        workspace_min_width 10
#        tray_output none
#        strip_workspace_numbers yes

#        status_command SCRIPT_DIR=$HOME/.config/i3/blocklets/ i3blocks

#        font pango:Cantarell 14

#        colors {
#        background    $dark
#        statusline    $white
#        separator     #555555

#        border     backgr    text
#        focused_workspace   $blue      $blue     $darker
#        active_workspace    $dark      $dark     $blue
#        inactive_workspace  $dark      $dark     $blue
#        urgent_workspace    $red       $red      $darker
#        }
            
#        colors {
#        background $inactive-bg-color
#        statusline $bg-color
              
#        border                         backgr                   Etext            
#        focused_workspace   $inactive-bg-color  $inactive-bg-color $text-color
#        active_workspace    $inactive-bg-color  $inactive-bg-color $inactive-text-color
#        inactive_workspace  $inactive-bg-color  $inactive-bg-color $inactive-text-color
#        urgent_workspace    $urgent-bg-color    $urgent-bg-color   $text-color
#        }

#        }
   
# Start i3bar to display a workspace bar (plus the system information i3status if available)
#bar {
#    i3bar_command i3bar 
#    status_command i3status
#    position bottom

# please set your primary output first. Example: 'xrandr --output eDP1 --primary'
#	tray_output primary
#	tray_output eDP1

#    bindsym button4 nop
#    bindsym button5 nop
#   font xft:URWGothic-Book 11
#   strip_workspace_numbers yes

#    colors {
#    set_from_resource $fg i3wm.color7 #f4dc98
#    set_from_resource $bg i3wm.color6 #0A1837
#        background $bg
#        statusline #F9FAF9
#        separator  #454947

#                      border  backgr. text
#        focused_workspace  #F9FAF9 $bg #292F34
#        active_workspace   #595B5B $bg #FDF6E3
#        inactive_workspace #595B5B $bg #EEE8D5
#        binding_mode       #16a085 $bg #F9FAF9
#        urgent_workspace   #16a085 $bg #E5201D
#    }
#}

# hide/unhide i3status bar
#bindsym $sup+m bar mode toggle
   
# ----------------------------------------------------------------------------
# I3BLOCKS
# ----------------------------------------------------------------------------

#i3blocks - keylock leds status
#bindsym --release Caps_Lock  $exe pkill -SIGRTMIN+11 i3blocks
#bindsym --release Num_Lock   $exe pkill -SIGRTMIN+11 i3blocks

# i3blocks - upgrades
#$ss+u                 $exe pkill -SIGRTMIN+14 i3blocks

## i3blocks volume control and status
#set $vol_signal pkill -SIGRTMIN+10 i3blocks

#$sup+F9                      $exe pavucontrol && $vol_signal
#$sup+F10                     $exe amixer set Master toggle && $vol_signal
#$sup+F11                     $exe amixer set Master playback 5%- unmute && $vol_signal
#$sup+F12                     $exe amixer set Master playback 5%+ unmute && $vol_signal

#XF86AudioRaiseVolume
#XF86AudioLowerVolume
#XF86AudioMute
