bar {
    position top
    font pango:Source Code Pro Semibold, FontAwesome 10
    status_command i3blocks
    colors {
        background #111111
#        statusline #dddddd
        separator #666666

        # class             border  bg      text
#        focused_workspace   #1170a0 #1170a0 #ffffff
#        active_workspace    #333333 #5f676a #ffffff
#        inactive_workspace  #333333 #222222 #888888
#        urgent_workspace    #2f343a #900000 #ffffff
#        binding_mode        #2f343a #900000 #ffffff
    }
}
