#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "PowerOff" {
	echo "Desligando o sistema..."
	halt
}

menuentry "Reboot" {
	echo "Reinicializando o sistema..."
	reboot
}

if [ ${grub_platform} == "efi" ]; then
	menuentry "UEFI Settings" {
		fwsetup
	}
fi
