[files]
recent_files=/home/sidiclei/.dotfiles/.gitignore;/home/sidiclei/.dotfiles/README.md;/home/sidiclei/.config/gtk-4.0/settings.ini;/home/sidiclei/.config/embellish/fonts;/home/sidiclei/.config/btop/btop.conf;/home/sidiclei/.config/Kvantum/kvantum.kvconfig;/home/sidiclei/.config/krulerrc;/home/sidiclei/.config/nody-greeter/Preferences;/home/sidiclei/.zshrc;/home/sidiclei/.config/kdeconnect/config;
recent_projects=
current_page=0
FILE_NAME_0=0;None;0;EUTF-8;1;1;0;%2Fhome%2Fsidiclei%2F.dotfiles%2F.gitignore;0;4

[project]
session_file=
project_file_path=/home/sidiclei/projects

[geany]
treeview_position=0
msgwindow_position=586
geometry=5;33;1356;730;1;
sidebar_page=1

[VTE]
last_dir=/home/sidiclei

[search]
find_all_expanded=true
replace_all_expanded=false
position_find_x=357
position_find_y=293
position_replace_x=337
position_replace_y=278
position_fif_x=429
position_fif_y=284

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=/usr/lib/geany/saveactions.so;
