Section "InputClass"
     Identifier "libinput touchpad catchall"
     MatchIsTouchpad "on"
     MatchDevicePath "/dev/input/event*"
     Driver "libinput"
     Option "Tapping" "true"
     Option "NaturalScrolling" "false"
     Option "ScrollMethod" "edge"
     Option "HorizontalScrolling" "true" 
     Option "TappingDrag" "true"
     Option "TappingButtonMap" "(lrm|lmr)"
    #Option "SendEventsMode" "disabled-on-external-mouse"
     Option "AccelSpeed" "0.5"
     Option "AccelProfile" "adaptive"
EndSection

 # Opção "SendEventsMode" "disabled-on-external-mouse" - Quando um mouse USB é detectado, ela desativa o touchpad.
 # Opção "Tapping" "True" - Permite que você use o dedo e toque no mouse para clicar. Se você deixar essa opção de fora, ela fará com que você tenha que clicar fisicamente no touchpad para ativar um clique do mouse ou usar os botões inferiores. Quando a opção for ativada, ela permitirá que dois toques com o dedo ativem um clique com o botão direito.
 # Opção "DisableWhileTyping" "True" - Essa opção é ativada por padrão, mas essa é a configuração, caso você queira saber.
 # Opção "AccelProfile" "adaptive" - Ativa o perfil de aceleração do mouse. Isso ajuda a tornar a velocidade do dedo do mouse um pouco mais natural e menos lenta. A opção 'adaptive' é recomendável, já que muda a velocidade conforme suas entradas. Você também pode tentar a opção "flat".
 # Opção "AccelSpeed" "0.3" - Altera a velocidade de aceleração do ponteiro. Use valores de -1 a 1. Quanto maior o número, mais rápido será o ponteiro. A maioria das pessoas gosta de usar 0,2 para uma resposta mais lenta e 0,5 para uma resposta mais rápida.
 # Opção "TappingDrag" "True" - Quando essa opção estiver ativada, um toque seguido de um pressionamento com o dedo causará o pressionamento de apenas um botão; assim, todos os movimentos desse dedo se traduzirão no movimento de arrasto.
 # Opção "HorizontalScrolling" "True" - Se você quiser conseguir rolar a tela de um lado para o outro. Pessoalmente, eu não gosto dessa opção. Se você tiver uma tela touchscreen, poderá usar a opção na tela touchscreen. A sensação é mais natural na tela touchscreen que no touchpad.
 # Opção "ScrollMethod" "edge" - Por padrão, o touchpad rola usando dois dedos. Se você gosta do estilo do mouse mais antigo que tinha a área de rolagem à direita do touchpad, você pode usar essa opção para ativá-la.
